INSERT INTO USER_MASTER(sr_no,USER_ID,USER_NAME) VALUES(5,'USERID0005','ABC');
INSERT INTO USER_MASTER(sr_no,USER_ID,USER_NAME) VALUES(6,'USERID0006','DEF');
INSERT INTO USER_MASTER(sr_no,USER_ID,USER_NAME) VALUES(7,'USERID0007','XYZ');